import { PrismaClient } from '@prisma/client';

export async function seedCompanies(prisma: PrismaClient) {
  const rawCompanies = [
    'BAHRI',
    'VENTOMOL',
    'PROCTO CINOLONE',
    'EVON',
    'PARADRIN',
    'RAMAPRED',
    'CLOTRIDERM',
    'UNISONIDE',
    'REVOSYL',
    'LYCO',
    'JOHNSON',
    'PAMPERS',
    'BIOGHAR',
    'PINOTEX',
    'CINOLON',
    'DITROSPAM',
    'METAPIROX',
    'ZINCAMIN',
    'CLAVUMAS',
    'CERAVE',
    'UNIFREX',
    'CORONASYL',
    'INDAPAMIDE',
    'AVICE',
    'LYCO CREAM',
    'UTROGESTAN',
    'ALEQUID',
    'ROSACREST',
    'ADENOXAT',
    'JOHNSON SHAMPOO',
    'BEBYLAND',
    'AMOKSIKLAV',
    'LOTILMOND',
    'NO VOMITA',
    'ZOLOSYR',
    'TAMSULOSIN',
    'LIPOSYR',
    'NUROFEN',
    'CLEAR SHAMPOO',
    'CIDAL',
    'DIGOXIN',
    'HYALO-VISCOUS',
    'COLGATE',
    'DOSAL',
    'RADINS',
    'CETACLENAC',
    'REVOSYL ARGININE',
    'HASYPYROXICAM',
    'CLEON SPRAY',
    'CINNARZINE',
    'UNIFREX CAP',
    'CORDAN',
    'IMILIN CREAM',
    'AVICE LOTION',
    'LUSTER',
    'UROMAX',
    'GLUCOPHAGE',
    'FINLEPSIN',
    'H Q VAGE',
    'POVIDON',
    'BURN HEAL CREAM',
    'PROBIOTIC',
    'FARBN',
    'CARDOM',
    'GLUCOSAMINE',
    'FISOHEAL CRAM',
    'HAIR AGAIN DERMAL SPRAY',
    'POWERGEL GEL',
    'BUSCOMED AMP',
    'KITKAT CHOCOLATE',
    'SERUM SERUM',
    'KLIOCIN',
    'BIOCARDIS',
    'METRODENT',
    'VITAPRESS',
    'ARIPIFY',
    'SKIN CARE',
    'DEANXIT',
    'KARAM SOAP',
    'BEDRANOL',
    'HYDROCORT',
    'RAMAPRED',
    'MITOSYL',
    'ZEERA',
    'FORMILAR PLUS INHALER',
    'LOBAB ALTABEEA',
    'CAPOTEN UNI',
    'PRIMO',
    'EZERAX',
    'CAVALI',
    'GRIPPADOL',
    'ACTINERVE',
    'ISONITRA',
    'MAGNESIUM',
    'VASELINE',
    'AMBROXOL',
    'SALBUVENT',
    'AILLIN',
    'CORABRADINE',
    'IDROCIL',
    'LEVOTHYROXINE',
    'UNI CYTEAL',
    'PANVENO',
    'EKLESIN',
    'TURINAL',
    'OTRIVIN',
    'DOVE',
    'BAKING DOUCHE',
    'MAXFIL',
    'SAMIRAH',
    'KERNEL',
    'BENZATHINE PENICILLIN',
    'MENTOGEL',
    'VISALGINE',
    'DEXAMED',
    'ANY KLEAN',
    'SHARK',
    "L'OURMAL",
    'REXONA',
    'INTENSIVE CARE',
    'AZIDIN',
    'LYCO',
    'VALSARTAN ACTIVE',
    'D-CURE',
    'ALLURIC',
    'ROVALTRO',
    'ADULT VIT',
    'JOLLYDENT',
    'ATORVASTATIN',
    'LUKAST',
    'VITA',
    'DEXAPOLYCID',
    'APIPOL',
    'SHIFFA',
    'LACTISYR',
    'BIODERMA',
    'MICONAZOLE',
    'ASCO ZINC',
    'PARAMAX',
    'PIZOFEN',
    'FLUTICASONE',
    'EVENTALEN',
    'BONEXIB',
    'PAVACORIUM',
    'BIOGHAR TRANS',
  ];

  // Remove duplicates
  const uniqueCompanies = [...new Set(rawCompanies)];

  for (const name of uniqueCompanies) {
    await prisma.company.upsert({
      where: { name },
      update: {},
      create: {
        name,
        email: `${name.toLowerCase().replace(/\s+/g, '')}@example.com`,
        phone: '+20123456789',
        address: 'Cairo, Egypt',
      },
    });
  }

  console.log(`✅ Seeded ${uniqueCompanies.length} companies`);
}
